#!/usr/bin/python3

import curses
from curses import wrapper
import time
import pyaudio
import wave
import time
import sys
import threading
import queue
from os import listdir
from os.path import isfile, join
from random import randint

from util import game
from util import record
from util import play
from util import audio
from util import song_util

TITLE_W = 42
TITLE_H = 11
TITLE_ART = """
   ______                                
  / ____/__  __ _____ _____ ___          
 / /    / / / // ___// ___// _ \         
/ /___ / /_/ // /   (__  )/  __/         
\____/ \__,_//_/   /____/ \___/          
    __  ___               _         __ __
   /  |/  /____ _ ____   (_)____ _ / // /
  / /|_/ // __ `// __ \ / // __ `// // / 
 / /  / // /_/ // / / // // /_/ //_//_/  
/_/  /_/ \__,_//_/ /_//_/ \__,_/(_)(_)
"""

CREDITS_W = 51
CREDITS_H = 4
CREDITS_ART = """
          Upsilon Pi Epsilon, UC Berkeley         
Alexander Kang, Michael Knyszek, Patrick McGartoll
                  Created 2015                    
"""

def renderTitleArt(stdscr):
    height, width = stdscr.getmaxyx()
    y = height // 3 - TITLE_H // 2
    x = width // 2 - TITLE_W // 2
    for line in TITLE_ART.split("\n"):
        stdscr.addstr(y, x, line, curses.A_BOLD)
        y += 1
    return (y, x)

def renderCreditsArt(stdscr, y, x):
    for line in CREDITS_ART.split("\n"):
        stdscr.addstr(y, x, line)
        y += 1

def renderTitleMenu(stdscr, menu, selected, y, x):
    r = y
    for i in range(len(menu)):
        if i == selected:
            stdscr.addstr(r, x, ">")
            stdscr.addstr(r, x + 2, menu[i], curses.A_BOLD)
        else:
            stdscr.addstr(r, x + 2, menu[i])
        r += 1

def renderFooter(stdscr):
    height, width = stdscr.getmaxyx()
    s = "q - Quit | Arrow Keys - Menu Selection | a - Continue | Game Controls - d f j k"
    stdscr.addstr(height-1, width // 2 - len(s) // 2, s)

# title is the title of the file menu you want
# location is the folder in which you'll be viewing files
# extension is the extension to filter by
# action is a function that takes stdscr and a file name
#   action, for example, is playing the game or recording notes for a song

def file_menu(stdscr, title, location, extension, action):
    height, width = stdscr.getmaxyx()
    
    f_selected = 0
    files = [f for f in listdir(location) if f.endswith(extension)]
    
    if len(files) == 0:
        return
    
    files.sort()
    view_top = 0
    view_bot = min(len(files)-1, height-7)
    
    while True:
        stdscr.clear()
        
        stdscr.addstr(1, width // 2 - len(title) // 2, title, curses.A_BOLD)
        stdscr.addstr(3, 4, "Track Name", curses.A_BOLD)
        
        s = "Viewing Tracks " + str(view_top + 1) + " to " + str(view_bot + 1) + " of " + str(len(files))
        stdscr.addstr(3, width - len(s) - 1, s)
        
        for i in range(width):
            stdscr.addch(4, i, "-")
            
        j = 5
        for i in range(view_top, view_bot+1):
            if i == f_selected:
                stdscr.addstr(j, 2, ">")
                stdscr.addstr(j, 4, files[i], curses.A_BOLD)
            else:
                stdscr.addstr(j, 4, files[i])
            j += 1
            
        k = stdscr.getch()
        if k == curses.KEY_DOWN:
            if f_selected != len(files) - 1:
                f_selected += 1
                if f_selected > view_bot:
                    view_bot += 1
                    view_top += 1
                    
        elif k == curses.KEY_UP:
            if f_selected != 0:
                f_selected -= 1
                if f_selected < view_top:
                    view_bot -= 1
                    view_top -= 1
        
        elif k == ord('a'):
            action(stdscr, files[f_selected])
        
        elif k == ord('q'):
            return
       

def main(stdscr):
    height, width = stdscr.getmaxyx()
    
    mm_selected = 0
    main_menu = ["Play", "Record", "Options"]
    
    while True:
        
        stdscr.clear()
        
        ta_y, ta_x = renderTitleArt(stdscr)
        renderTitleMenu(stdscr, main_menu, mm_selected, ta_y + 3, ta_x + TITLE_W // 3)
        renderCreditsArt(stdscr, ta_y + 9, width // 2 - CREDITS_W // 2)
        renderFooter(stdscr)
        
        k = stdscr.getch()
        
        if k == curses.KEY_DOWN:
            mm_selected = (mm_selected + 1) % len(main_menu) 
            
        elif k == curses.KEY_UP:
            mm_selected = (mm_selected - 1) % len(main_menu)
            
        elif k == ord('a'):
            selection = main_menu[mm_selected]
            if selection == "Play":
                file_menu(stdscr, "PLAY THE GAME!!", song_util.DIR_SONGS, ".txt", game.game)
            elif selection == "Record":
                file_menu(stdscr, "CHOOSE A SONG TO RECORD NOTES FOR", song_util.DIR_WAV, ".wav", record.record)
                
        elif k == ord('q'):
            return
        

wrapper(main)
